
declare type ERR_CONST = number

declare var OK: ERR_CONST

declare var ERR_NOT_OWNER: ERR_CONST
declare var ERR_NO_PATH: ERR_CONST
declare var ERR_NAME_EXISTS: ERR_CONST
declare var ERR_BUSY: ERR_CONST
declare var ERR_NOT_FOUND: ERR_CONST
declare var ERR_NOT_ENOUGH_ENERGY: ERR_CONST
declare var ERR_NOT_ENOUGH_RESOURCES: ERR_CONST
declare var ERR_INVALID_TARGET: ERR_CONST
declare var ERR_FULL: ERR_CONST
declare var ERR_NOT_IN_RANGE: ERR_CONST
declare var ERR_INVALID_ARGS: ERR_CONST
declare var ERR_TIRED: ERR_CONST
declare var ERR_NO_BODYPART: ERR_CONST
declare var ERR_NOT_ENOUGH_EXTENSIONS: ERR_CONST
declare var ERR_RCL_NOT_ENOUGH: ERR_CONST
declare var ERR_GCL_NOT_ENOUGH: ERR_CONST

declare type FIND_CONST = number

declare var FIND_EXIT_TOP: FIND_CONST
declare var FIND_EXIT_RIGHT: FIND_CONST
declare var FIND_EXIT_BOTTOM: FIND_CONST
declare var FIND_EXIT_LEFT: FIND_CONST
declare var FIND_EXIT: FIND_CONST
declare var FIND_CREEPS: FIND_CONST
declare var FIND_MY_CREEPS: FIND_CONST
declare var FIND_HOSTILE_CREEPS: FIND_CONST
declare var FIND_SOURCES_ACTIVE: FIND_CONST
declare var FIND_SOURCES: FIND_CONST
declare var FIND_DROPPED_ENERGY: FIND_CONST
declare var FIND_DROPPED_RESOURCES: FIND_CONST
declare var FIND_STRUCTURES: FIND_CONST
declare var FIND_MY_STRUCTURES: FIND_CONST
declare var FIND_HOSTILE_STRUCTURES: FIND_CONST
declare var FIND_FLAGS: FIND_CONST
declare var FIND_CONSTRUCTION_SITES: FIND_CONST
declare var FIND_MY_SPAWNS: FIND_CONST
declare var FIND_HOSTILE_SPAWNS: FIND_CONST
declare var FIND_MY_CONSTRUCTION_SITES: FIND_CONST
declare var FIND_HOSTILE_CONSTRUCTION_SITES: FIND_CONST
declare var FIND_MINERALS: FIND_CONST
declare var FIND_NUKES: FIND_CONST

declare type CREEP_BODY_PART = string

declare var MOVE: CREEP_BODY_PART
declare var WORK: CREEP_BODY_PART
declare var CARRY: CREEP_BODY_PART
declare var ATTACK: CREEP_BODY_PART
declare var RANGED_ATTACK: CREEP_BODY_PART
declare var TOUGH: CREEP_BODY_PART
declare var HEAL: CREEP_BODY_PART
declare var CLAIM: CREEP_BODY_PART

declare type RESOURCE_CONST = string

declare var RESOURCE_ENERGY: RESOURCE_CONST
declare var RESOURCE_POWER: RESOURCE_CONST

declare var RESOURCE_HYDROGEN: RESOURCE_CONST
declare var RESOURCE_OXYGEN: RESOURCE_CONST
declare var RESOURCE_UTRIUM: RESOURCE_CONST
declare var RESOURCE_LEMERGIUM: RESOURCE_CONST
declare var RESOURCE_KEANIUM: RESOURCE_CONST
declare var RESOURCE_ZYNTHIUM: RESOURCE_CONST
declare var RESOURCE_CATALYST: RESOURCE_CONST
declare var RESOURCE_GHODIUM: RESOURCE_CONST

declare var RESOURCE_HYDROXIDE: RESOURCE_CONST
declare var RESOURCE_ZYNTHIUM_KEANITE: RESOURCE_CONST
declare var RESOURCE_UTRIUM_LEMERGITE: RESOURCE_CONST

declare var RESOURCE_UTRIUM_HYDRIDE: RESOURCE_CONST
declare var RESOURCE_UTRIUM_OXIDE: RESOURCE_CONST
declare var RESOURCE_KEANIUM_HYDRIDE: RESOURCE_CONST
declare var RESOURCE_KEANIUM_OXIDE: RESOURCE_CONST
declare var RESOURCE_LEMERGIUM_HYDRIDE: RESOURCE_CONST
declare var RESOURCE_LEMERGIUM_OXIDE: RESOURCE_CONST
declare var RESOURCE_ZYNTHIUM_HYDRIDE: RESOURCE_CONST
declare var RESOURCE_ZYNTHIUM_OXIDE: RESOURCE_CONST
declare var RESOURCE_GHODIUM_HYDRIDE: RESOURCE_CONST
declare var RESOURCE_GHODIUM_OXIDE: RESOURCE_CONST

declare var RESOURCE_UTRIUM_ACID: RESOURCE_CONST
declare var RESOURCE_UTRIUM_ALKALIDE: RESOURCE_CONST
declare var RESOURCE_KEANIUM_ACID: RESOURCE_CONST
declare var RESOURCE_KEANIUM_ALKALIDE: RESOURCE_CONST
declare var RESOURCE_LEMERGIUM_ACID: RESOURCE_CONST
declare var RESOURCE_LEMERGIUM_ALKALIDE: RESOURCE_CONST
declare var RESOURCE_ZYNTHIUM_ACID: RESOURCE_CONST
declare var RESOURCE_ZYNTHIUM_ALKALIDE: RESOURCE_CONST
declare var RESOURCE_GHODIUM_ACID: RESOURCE_CONST
declare var RESOURCE_GHODIUM_ALKALIDE: RESOURCE_CONST

declare var RESOURCE_CATALYZED_UTRIUM_ACID: RESOURCE_CONST
declare var RESOURCE_CATALYZED_UTRIUM_ALKALIDE: RESOURCE_CONST
declare var RESOURCE_CATALYZED_KEANIUM_ACID: RESOURCE_CONST
declare var RESOURCE_CATALYZED_KEANIUM_ALKALIDE: RESOURCE_CONST
declare var RESOURCE_CATALYZED_LEMERGIUM_ACID: RESOURCE_CONST
declare var RESOURCE_CATALYZED_LEMERGIUM_ALKALIDE: RESOURCE_CONST
declare var RESOURCE_CATALYZED_ZYNTHIUM_ACID: RESOURCE_CONST
declare var RESOURCE_CATALYZED_ZYNTHIUM_ALKALIDE: RESOURCE_CONST
declare var RESOURCE_CATALYZED_GHODIUM_ACID: RESOURCE_CONST
declare var RESOURCE_CATALYZED_GHODIUM_ALKALIDE: RESOURCE_CONST

declare type Struct_Const = string

declare var STRUCTURE_SPAWN: Struct_Const
declare var STRUCTURE_EXTENSION: Struct_Const
declare var STRUCTURE_ROAD: Struct_Const
declare var STRUCTURE_WALL: Struct_Const
declare var STRUCTURE_RAMPART: Struct_Const
declare var STRUCTURE_KEEPER_LAIR: Struct_Const
declare var STRUCTURE_PORTAL: Struct_Const
declare var STRUCTURE_CONTROLLER: Struct_Const
declare var STRUCTURE_LINK: Struct_Const
declare var STRUCTURE_STORAGE: Struct_Const
declare var STRUCTURE_TOWER: Struct_Const
declare var STRUCTURE_OBSERVER: Struct_Const
declare var STRUCTURE_POWER_BANK: Struct_Const
declare var STRUCTURE_POWER_SPAWN: Struct_Const
declare var STRUCTURE_EXTRACTOR: Struct_Const
declare var STRUCTURE_LAB: Struct_Const
declare var STRUCTURE_TERMINAL: Struct_Const
declare var STRUCTURE_CONTAINER: Struct_Const
declare var STRUCTURE_NUKER: Struct_Const
