
export const HARVESTER_ROLE = "HARVESTER"
export const UPGRADER_ROLE = "UPGRADER"
export const HAULER_ROLE = "HAULER"

export const HAULER_COLLECT_JOB = "HAULER_COLLECT_JOB"
export const HAULER_TRANSPORT_JOB = "HAULER_TRANSPORT_JOB"
