
export const HARVESTER_ROLE = "HARVESTER"
export const UPGRADER_ROLE = "UPGRADER"
export const HAULER_ROLE = "HAULER"
export const BUILDER_ROLE = "BUILDER"

export const HAULER_COLLECT_JOB = "HAULER_COLLECT_JOB"
export const HAULER_TRANSPORT_JOB = "HAULER_TRANSPORT_JOB"

export const BUILDERS_PER_ROOM = 2

export const BARE_BONES_HARVESTERS_PER_SOURCE = 2
export const BASIC_INFRA_HARVESTERS_PER_SOURCE = 1

export const HAULERS_PER_COLLECT_TARGET = 1
export const HAULERS_PER_TRANSPORT_TARGET = 1

export const BARE_BONES_UPGRADERS_PER_CONTROLLER = 1
export const BASIC_INFRA_UPGRADERS_PER_CONTROLLER = 2

